---
title: "POLS102 Section 01 Spring 2022 Syllabus"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    toc_depth: 4
    self_contained: no
  word_document:
    toc: no
    toc_depth: '4'
  pdf_document:
    toc: no
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


POLS102: Comparative Politics
Section 1
Monday, Wednesday, and Friday  10:20am - 11:20am
JR Howard 259
Lewis & Clark College   
Spring 2022

Ian R. McDonald, Ph.D.  
ianmcdonald@lclark.edu  
Office:  Miller Hall 434  
Phone: +1.503.768.7456 
Zoom PMI: 508 354 7883


Office Hours:   
Monday and Wednesday 3:30-5 + email or additional times by appointment. You can meet with me in person or via teleconferencing.  

## Google Classroom

Our class portal will be stored in Google Classroom.  From there, you should be able to find links to the online version of the syllabus, which will have links to all the readings.  In addition, Google Classroom will contain links for you to upload class assignments, read announcements, and find copies of  assigned readings.

On the first day of class, you should respond to the Google Classroom invitation link at https://classroom.google.com/c/NDUwMzY0NzIwMzk5?cjc=zbjwhpr.  The Class Code is zbjwhpr.  This link should take you directly to the class once you have signed up for it:
https://classroom.google.com/u/0/c/NDUwMzY0NzIwMzk5

My goal is to make this course entirely accessible using online content.  Except for one assigned paperback book, expect to find everything you need from the Google Classroom portal.

### Finding this Syllabus

This syllabus is an [online web page](https://pols-102-comparative-politics-spring2022.netlify.app/syllabus.html), though a [PDF version](https://pols-102-comparative-politics-spring2022.netlify.app/syllabus.pdf) is available.  You can access the syllabus at this link: https://pols-102-comparative-politics-spring2022.netlify.app/syllabus.html.  Google Classroom provides a link to the syllabus at the top of Classwork section.

### Course Description
What are the prospects for democracy in Egypt, Zimbabwe, or China?  Why do countries like Afghanistan, Somalia, and Syria suffer from political instability and violence?  Comparative politics seeks to answer these and similar questions by understanding and comparing political behavior and institutions in countries throughout the world. 
 
The goal of this course is to introduce students to the key theoretical frameworks and analytical methods in the field of comparative politics.  We will start by asking the question "What are that problems that any effective political system must resolve"?  We will then review the three major theoretical lenses in comparative politics by analyzing the extended example of democracy and its causes.  While continually drawing on our methodological toolkit throughout the course, we will then analyze a variety of topics such as state-building and ethnic conflict.

Each week we will read a diverse set of articles involving research from different areas of the world.  Students will therefore have the chance to expand and hone their comparative as well as analytic thinking skills.  Students can expect to read predominantly scholarly articles, but will also be exposed to various materials from the news media or films.  Overall, this course should prepare students to engage in comparative politics in a variety of settings, be they academic or otherwise.
 
### Learning Goals

Learning is an interactive process that requires active engagement by the professor and students. 

After taking this class students should be able to:

* Demonstrate basic fluency in the main concepts and terms of comparative politics (e.g., the state, regime, and nation-state).  

* Explain the main ways that societies vary (in their institutions, resources, and culture), and how this variation influences important political, social, or economic outcomes (e.g., form of democratic governance, ethnic conflict, or economic growth).  

* Describe the political context of a region or regions of the world beyond the United States (through reading, writing, conversation, presentation and/or first-hand experiences). Topics of study include historical experience, cultural traditions, past and current social and economic realities, or transnational issues.  

* Apply empirically based criteria, rather than just opinion, to assess the merits of a theory or argument.  For example, students will learn how to identify the structure of a scholarly argument ("why might X1 *cause* Y, but X2 would not not cause Y"), and the logic of the argument ("why does X lead to Y?").  Students will learn how to communicate this assessment in both oral and written form.  

* Improve, with practice, the ability to craft an argument in written form that is appropriately structured and well written stylistically.  

### Course Materials

You will need access to a copy of one book:      
**Ezrow, Natasha M. and Erica Frantz.  2011.  *Dictators and Dictatorships: Understanding Authoritarian Regimes and Their Leaders.*  Bloomsbury. ISBN 978-1-4411-7896-6.** 

The book is available in ebook format at https://ebookcentral.proquest.com/lib/lewisclark/reader.action?docID=661026

All other assigned readings are online and accessible in the Google Classroom site or directly at the source website.  Links are also available in the online version of this syllabus.  See the links in the syllabus class schedule for details.

##  Course Expectations and Rules 
### Reading  

There is generally more than one reading assigned for each day. The class will introduce you to the many voices that form the conversation about comparative politics. Additionally, this class will ask you to practice your abilities moving from theory to specific case studies or examples.  

The assigned readings are short and you should plan to read all of them carefully in their entirety before we start each class.
 
Students should be prepared to answer the following three questions each class period:  

1. What is the main question that animates the reading?  
2. What case(s) are used to answer the main question?  
3. In one or two sentences, what is the main answer to the question?

You will find a reading guides for individual readings here:  https://classroom.google.com/c/NDUwMzY0NzIwMzk5/m/NDUxMTIwMTY3NzAx/details

You will find a more general guide How to Read Works in comparative politics:  
https://classroom.google.com/c/NDUwMzY0NzIwMzk5/m/NDUxMTIxODc2NjQ2/details

### Phones and Laptops.

Phones and laptops are permitted. But when we're in class, be present. Do not allow your devices to distract you or anyone else. 

Be mindful that we have a very limited amount of time together.  Be present.

### Recording classes.

Lewis & Clark policy generally forbids recording of classes.  The policy states: "...the secret recording (audio or video) of classes, meetings or other conversations, including telephone calls, is prohibited, as not compatible with the law or the promotion of an open exchange of ideas." 

Please do not record classes without discussing it with me. The concern is protecting privacy, for everyone in the classroom.  See me if you have questions.  The policy is available at https://www.lclark.edu/live/profiles/3606-recording-policy.

### Health and Safety Expectations
The College’s health and safety guidelines are applied in all settings across campus and comply with county guidelines.  We each share responsibility to keep our community healthy by adhering to the following expectations: 

* Wear a face covering when inside, even when physical distancing can be maintained, and outside when physical distancing cannot be maintained.

* Stay at home if you have any of the following COVID symptoms, including cough, fever or chills, shortness of breath, difficulty breathing, muscle pain, headache, sore throat, new loss of taste or smell, diarrhea, nausea, vomiting, nasal congestion, or runny nose.

If you experience symptoms, please take the following steps:\

* Complete the online notification form, available on the Health Information Portal. This will help us track possible COVID cases on campus to keep us all safe.  Information on COVID symptoms can be found on the LC Health and Safety Expectations webpage and on the CDC webpage. The College is also encouraging use of a self-monitoring app. Information on the app - Campus Clear - can be found here.

* Contact your professor and attend your course virtually.  If you live off campus, do not come to campus.  

* Follow the advice by health care providers and student life staff regarding quarantine. More information on that can be found here. 

### Academic Honesty
The [Lewis & Clark Code of Student Conduct](https://college.lclark.edu/student_life/-our-departments-/student-rights-responsibilities/student-code-of-conduct/) is in force at all times.  Note that the consequences for plagiarism and cheating are extremely serious.

Failure to meet the expectations for conduct will result in a reduction of your final grade.

### Accommodation
If you have a disability that may impact your academic performance, you may request accommodations by submitting documentation to the Student Support Services Office in Albany Quadrangle (you can use their online scheduling system to book a Zoom or phone appointment). After you have submitted documentation and filled out paperwork there for the current semester requesting accommodations, staff in that office will notify me of the accommodations for which you are eligible. 

### Course Withdrawals
You may drop this course on WebAdvisor by Friday, January 28 at 4pm and no W grade will appear on your transcript. From then until 4pm on Friday, April 1, you can withdraw from the course by submitting a Course Withdrawal form to the Registrar’s Office. In this case, a W grade will appear on your transcript.  
I cannot authorize your withdrawal from the course after April 1. At that point, you will need to complete the course and take whatever grade you have earned. If you have questions or concerns about your performance in the course, please talk with me or write me anytime.

## Assignments and Key Dates

### Assignments

#### February 4  
Pass/Fail Assignment 1  
https://classroom.google.com/c/NDUwMzY0NzIwMzk5/a/NDUxNjIwMjM4NDUx/details

#### March 9  
Pass/Fail Assignment 2  
https://classroom.google.com/c/NDUwMzY0NzIwMzk5/a/NDUxNjY3NDE1MjM3/details

#### April 18  
Pass/Fail Assignment 3  
https://classroom.google.com/c/NDUwMzY0NzIwMzk5/a/NDUxNjc1MzAzNTUw/details

### Essays

#### March 18    
Paper 1 Reading Analysis   
https://classroom.google.com/c/NDUwMzY0NzIwMzk5/a/NDUxNjcwMDg4MDI1/details

#### April 27  
Paper 2 Analytic Essay  
https://classroom.google.com/c/NDUwMzY0NzIwMzk5/a/NDUxNjc3Mzg4MDY1/details

### Exams  

#### February 23  
Midterm Exam

#### May 4 1-4pm
Final Exam

## Course Grading

**Midterm Exam (20%) and Final Exam (25%)**  

**Attendance (5%)**    
Attendance will be taken at every session.  If you must miss a session, please notify me in advance (email is fine).  

Attending consistently is the easiest thing you can do to improve your grade and improve your overall class experience, and not just because of this particular attendance requirement. If you have many absences or must be gone for an extended period of time, I may ask you to document your excuse and I may suggest you to withdraw from the course.  

**Participation and Pass/Fail Assignments (5%)**   
Throughout the course we will be doing several forms of in-class activity that require active participation: all-class discussion, cohort work, or answering polls or surveys of the class.  Group work is very important and active participation during group work is necessary. Throughout the course of the semester there will be pass/fail assignments in which students will apply class themes and topics to a country case of their choosing that will count towards participation.    

**Paper 1: Reading Analysis (3-4 page paper) (20%)**   
You will be given a academic reading in comparative politics. You will be required to identify the research question, findings and method, and discuss how the study fits into broader themes in the course.  You will also evaluate whether (and why) you found the study compelling.  Additional instructions for this paper will be distributed in class.\

**Paper 2: Analytic Essay (6-8 pages) (25%)**\  
This essay builds on the work that you will conduct in the country based pass/fail assignments.  You will compare the regime type of your country case and another country in its region.  You will identify a theory from class readings that could explain the similarity or differences in regime type and then will test this theory in the cases.  Students will draw on course readings as well as outside research. Additional instructions for this paper will be distributed in class.\

Students must complete all work. None of the assignments are optional.
 
### Late Assignments

All assignments are expected to be turned in on time as designated by the prompt connected with the assignment.  Assignments will all be submitted via google classroom using the “turn it in” button associated with the assignment.\

An assignment will be considered “late” if submitted after the designated deadline.  In the first 24 hours after the designated deadline has passed, the assignment will receive a penalty of one-third of a letter grade (e.g. from a B to B-).  Every subsequent 24 hours an assignment is late, an additional one-third penalty will be assessed.  For example, if a B paper is turned in three days late, the student would receive a C.    

### Paper Grading Rubric
A: Outstanding work.  The paper shows creativity, insight, and is analytically sound. The argument is well structured and overall the paper displays a sophisticated writing style (syntax, grammar).  

B: Good, above average work.  The paper shows mastery of the main concepts and ideas, but does not necessarily synthesize them in an original form.  The paper’s structure and syntax are generally fine, but there may be some writing issues present.  

C: Average work.  Shows some mastery of the main concepts and ideas, but more generally does not.  There are also structure and syntax problems present.  

D: Work reflects some effort or attempt to engage the task but is unsatisfactory as a final product, either because a key expectation of the task has been ignored or there is no evidence of mastery of the essential content.  

F: Does not meet minimum requirements.   

If this rubric seems unclear to you, please see me.

### Reading Guide
Review this document for help with the individual readings (also noted above)

The library supports the country assignments described in Google and provides a helpful set of resources at https://library.lclark.edu/c.php?g=908438

## Course Schedule  

Readings can be found in one of three places:  

* Google Drive at https://drive.google.com/drive/u/0/folders/1PycwTQFsX2KtsrT6kgDJDl95xJ4HpXgv

* The link shown below.  For periodicals and news sites, you will usually link directly to the host site.  

* The Ezrow and Frantz book.  See the Course Materials section for details.    


### Week 1
#### Wednesday, January 19

Zoom link:  
https://zoom.us/j/5083547883?pwd=QzVVNG5QMjJSTUlPZ1JTSWszQitTZz09

**Topics:**

* Course introduction, syllabus review, and intro to Google Classroom
* What do mean when we talk about political systems? What are they expected to do?

Read the syllabus and come on Thursday with any questions that you have.  

#### Friday, January 21

Zoom link:  
https://zoom.us/j/5083547883?pwd=QzVVNG5QMjJSTUlPZ1JTSWszQitTZz09
**Topics:**  

* What is Comparative Politics?  What makes a good comparison?  

**Readings:**  

* Samuels, David. 2013. “Doing Comparative Politics.”  In Comparative Politics.  New York:  Pearson. Read pages 8-17 https://drive.google.com/file/d/1a6NOS9Tuuie_XJFcBPdcnR5zUKSrcK3_/view?usp=sharing

### Week 2
#### Monday, January 24

Zoom link:  
https://zoom.us/j/5083547883?pwd=QzVVNG5QMjJSTUlPZ1JTSWszQitTZz09

**Topics:**  

* What makes a good comparison between political systems?  How objective are our comparisons?   

**Readings:**  

* Art, David. 2011. “Introduction.” In Inside the Radical Right:  The Development of Anti-Immigrant Parties in Western Europe.  Cambridge:  Cambridge University Press.  Read pages 1-10. https://drive.google.com/file/d/1LvXOz5Cpa0pzHEbU134qIqDYbJvx3U_N/view?usp=sharing

* Wearing, David. 2010. “How Scientific is Political Science?” The Guardian. March 8, 2010.
https://www.theguardian.com/commentisfree/2010/mar/08/political-science-moral-ethical  

#### Wednesday, January 26

Zoom link:  
https://zoom.us/j/5083547883?pwd=QzVVNG5QMjJSTUlPZ1JTSWszQitTZz09

**Topic:**  

* Concept example: What is democracy?    

**Readings:**   

* Przeworski, Adam, Michael Alvarez, Jose Cheibub, and Fernando Limongi. 2000. “Democracy and Dictatorship.” In *Democracy and Development:  Political Institutions and Well-Being in the World, 1950-1990*. New York:  Cambridge University Press, 2000. Read pages 14-18. https://drive.google.com/file/d/18iRK5FkwDO8Ah9p0XBCvgtuzeCcGSwGs/view?usp=sharing

* Diamond, Larry. 1999. “Defining and Developing Democracy.”  In *Developing Democracy: Toward Consolidation*. Baltimore:  Johns Hopkins University Press. Read pages 7-19  https://drive.google.com/file/d/1gVG5ZS_7T5DXPVbk72N6tYBflulMzN2X/view?usp=sharing

#### Friday, January 28

Zoom link:  
https://zoom.us/j/5083547883?pwd=QzVVNG5QMjJSTUlPZ1JTSWszQitTZz09

* How do you measure democracy?  

**Readings**

* Gunitsky, Seva. 2015. “How Do You Measure ‘Democracy’?’” The Washington Post: Monkey Cage. June 23, 2015. http://www.washingtonpost.com/blogs/monkey-cage/wp/2015/06/23/how-do-you-measure-democracy/?wpisrc=nl_cage&wpmm=1   

* Read opening sections until “Methodology Questions” regarding Freedom House’s measure of democracy: https://freedomhouse.org/reports/freedom-world/freedom-world-research-methodology 

**Assignment:**  

Select any country that interests you from this list and has a population of over 10 million people. Do not pick the U.S.  http://worldpopulationreview.com/countries/    

* Please make your selection carefully, as you will follow this country throughout the semester in a series of pass/fail assignments and in paper #2.  

* Note Freedom House’s classification of your country and be ready to report this classification in class. https://freedomhouse.org/report/freedom-world.  

* Record your choice in a Google document using the Add/Create button. The assignment link in Google Classroom is found at https://classroom.google.com/c/NDUwMzY0NzIwMzk5/a/NDUxNjEzNDkzNDE4/details


### Week 3

#### Monday, January 31  

Zoom link:  
https://zoom.us/j/5083547883?pwd=QzVVNG5QMjJSTUlPZ1JTSWszQitTZz09

**Topics:**     

* Theory and Evidence in Comparative Politics.  Note: we will examine the causes of democracy based on the three theoretical lenses of comparative politics. Throughout our examination we will analyze the case of Egypt after the Arab Spring.    

* Democratization and the Arab Spring: The Cases of Egypt and Tunisia    

**Reading:**    

* Gelvin, James. 2012.  The Arab Uprisings: What Everyone Needs to Know. Oxford University Press. Read pages from bottom of page 33-40 (How entrenched were autocracies ruling Tunisia and Egypt); 42 (Who led the Egyptian uprising in Cairo); 45-48; 49 (What changes did the uprising in Egypt bring about?).  
http://ebookcentral.proquest.com/lib/lewisclark/reader.action?docID=886540

* Ghannouchi, Rached. 2021. My Country Has Been a Dictatorship Before. We Can’t Go Back. *New York Times* July 30, 2021.  https://www.nytimes.com/2021/07/30/opinion/tunisia-protests-rached-ghannouchi.html?action=click&module=Opinion&pgtype=Homepage.  PDF available at https://drive.google.com/file/d/1cx2OzusVjOEa4DKDtugmoH_ctI22x5Ws/view?usp=sharing

Recommended: Explore: http://guides.library.cornell.edu/c.php?g=31688&p=200748       

#### Wednesday, February 2

Zoom link:  
https://zoom.us/j/5083547883?pwd=QzVVNG5QMjJSTUlPZ1JTSWszQitTZz09

**Topic:**  

* What is a cultural approach? How might culture influence democratization?  

**Readings:**  

* Drogus, Carol Ann and Stephen Orvis. 2011. “What Explains Political Behavior?  Culture and Ideology.” from *Introducing Comparative Politics:  Concepts and Cases in Context*. Los Angeles:  Sage. Read pages 20-25. https://drive.google.com/file/d/1asdOtO0T9Hg-1kHJC6CpTuzbOY_n95ji/view?usp=sharing

* Putnam, Robert. 1993.  Making Democracy Work:  Civic Traditions in Modern Italy. Princeton:  Princeton University Press. Read pages 87-99, 115. https://drive.google.com/file/d/1XjoMAzLOpoZg0M7xrG2kn7lKxJpU16XP/view?usp=sharing

* Clemens, Walter. 2013. “Democracy as Chimera” The New York Times. September 20, 2013.  http://www.nytimes.com/2013/09/11/opinion/global/democracy-as-chimera.html?src=rechp PDF available at https://drive.google.com/file/d/1rO7JNo76wZGyOVGwoQw_qfSoSuAjWrLS/view?usp=sharing


#### Friday, February 4

Zoom link:  
https://zoom.us/j/5083547883?pwd=QzVVNG5QMjJSTUlPZ1JTSWszQitTZz09

* Drogus, Carol Ann and Stephen Orvis. 2011.  “What Explains Political Behavior?  Underlying Structures.” In Introducing Comparative Politics:  Concepts and Cases in Context. Los Angeles: Sage. Read pages 25-26. https://drive.google.com/file/d/1asdOtO0T9Hg-1kHJC6CpTuzbOY_n95ji/view?usp=sharing

* Ezrow and Frantz. 2011. “Factors Conducive to Democratization.”  In *Dictators and Dictatorships: Understanding Authoritarian Regimes and their Leaders.* Read pages 28-32 in chapter 2.  Available as ebook at https://ebookcentral.proquest.com/lib/lewisclark/reader.action?docID=661026

**Assignment:**  
Pass/Fail Assignment #1 in Google Classroom is Due. https://classroom.google.com/c/NDUwMzY0NzIwMzk5/a/NDUxNjIwMjM4NDUx/details


### Week 4

#### Monday, February 7
  
**Topic:**  

* What is a structural approach? How can structure influence democratization?  

**Readings:**  

* Rueschemeyer, Dietrich, Evelyne Huber Stephens, and John D. Stephens. 1992.  “Introduction: The Problem of Capitalist Development and Democracy.” In Capitalist Development and Democracy. Chicago:  University of Chicago Press. Read pages 1-12  As you read, try to map out the argument into a causal statement.  I will refer to this reading as RSS.  https://drive.google.com/file/d/1r3pCfvcc1UodzLqD2O4EybCKc9VAF1YF/view?usp=sharing 

RSS employ class analysis in this selection. A rough guide to social class distinctions in Rueschemeyer, Stephens, and Stephens:
Peasants: have small or no landholdings in rural areas
Working class: employed in manual labor outside of agriculture
Urban and petty bourgeoisie: merchants, craftsmen, small farmers, and other self-employed groups with few employees [often referred to as the middle class]
Bourgeoisie:  owners of capital (factories, large businesses), the main capitalist class
Landed elites: large landowners, can be descendants of feudal aristocracy

NEWS APPLICATION TO EGYPT.  Compare how this article differs from the op-ed by Clemens from February 3rd.
 Friedman, Thomas. 2013. “Close to the Edge.” The New York Times. August 20, 2013.  http://www.nytimes.com/2013/08/21/opinion/friedman-close-to-the-edge.html?_r=0 PDF at https://drive.google.com/file/d/1gSJksmvK7VtmbBephl-hHYdT3VOqTfCe/view?usp=sharing

#### Wednesday, February 9

What is a rational approach?  How does rationality influence democratization?

Drogus, Carol Ann and Stephen Orvis. 2011.  “What Explains Political Behavior? Individual Motivation.” In Introducing Comparative Politics:  Concepts and Cases in Context. Los Angeles:  Sage. Read pages 19-20, 28-29. https://drive.google.com/a/lclark.edu/file/d/0B1U-95UvxaafX1hCaThFWVBoSDg/view?usp=sharing	

https://drive.google.com/a/lclark.edu/file/d/0B1U-95Uvxaafd1lmN25oOWFRT00/view?usp=sharing
 
Levi, Margaret. 1997. “A Model, A Method, And a Map:  Rational Choice In Comparative Historical Analysis.” In Comparative Politics:  Rationality, Culture, and Structure (Cambridge:  Cambridge University Press, 1997), pp. 23-27. https://drive.google.com/a/lclark.edu/file/d/0B1U-95UvxaafalJLUzNBZVN1VXc/view?usp=sharing

Przeworski, Adam. 1991. “Democracy.” In Democracy and the Market. Cambridge:  Cambridge University Press. Read pages 10-19, First paragraph under heading “Democracy is Equilibrium” on page 26. https://drive.google.com/a/lclark.edu/file/d/0B1U-95UvxaafRHRVbXNiNmN5ME0/view?usp=sharing


#### Friday, February 11

How does rationality influence democratization?

Welzel, Christian. 2009. “Elite Pacts, Mass Mobilization, and Democratization.” Oxford:  Oxford University Press. Read pages 82-83. https://drive.google.com/open?id=1cH6icdgbINDzBVPZuCGTQFvmce6q3Eeh

O’Donnell, Guillermo and Philippe Schmitter. 1986. “Pacts.” In *Transitions from Authoritarian Rule:  Tentative Conclusions about Uncertain Democracies.* Baltimore:  Johns Hopkins University Press. Read pages 37-39. https://drive.google.com/a/lclark.edu/file/d/0B1U-95UvxaafaHVfN2V1eHVhVzg/view?usp=sharing

Wickham, Carrie. 2013.  “Egypt’s Missed Opportunity.” *The New York Times*. July 27, 2013. http://www.nytimes.com/2013/07/28/opinion/sunday/egypts-missed-opportunity.html?pagewanted=all PDF at https://drive.google.com/file/d/1DFxCscRp8T-25bZAr8WlVEEcFTeRhIqf/view?usp=sharing

Recommended: Boduszyński, Mieczysław P. and Sabina Henneberg. 2018. "Why the prospects for democracy are so much better in Tunisia than Egypt or Libya" *Washington Post* July 20, 2018. https://www.washingtonpost.com/news/monkey-cage/wp/2018/07/20/how-new-governments-deal-with-old-elites-matters-more-than-you-might-expect/ PDF at https://drive.google.com/file/d/1kPbNfO0XGqyFofLEA_bo7ae_4F1K8pal/view?usp=sharing

Recommended: Robinson, Kali. 2020. The Arab Spring at Ten Years: What’s the Legacy of the Uprisings? *Foreign Affairs* December 3, 2020 
https://www.cfr.org/article/arab-spring-ten-years-whats-legacy-uprisings

### Week 5

#### Monday, February 14

* States and Nations:  The Building Blocks of Political Order
* What is the state and what are its origins?  

**Readings:**  

* Drogus, Carol Ann and Stephen Orvis. 2019.  “The State.” In Introducing Comparative Politics:  Concepts and Cases in Context. Los Angeles:  Sage. Read pages 36-40.    
https://drive.google.com/file/d/11F4XjJkqXNZ6jeyTDxCYaD4weYcf77ur/view?usp=sharing

* Tilly, Charles. 1985. “War Making and State Making as Organized Crime.” In Bringing the State Back In, edited by Peter Evans, Dietrich Ruschemeyer, and Theda Skocpol, READ 169-175 (stop at Protection as Business), 181 (Begin What Do States Do?)-186.  
https://drive.google.com/file/d/1oNZOGEXarDaADVWCOH65xxjRd-YoPqyL/view?usp=sharing

#### Wednesday, February 16

**Topic:**  

* What is the historical sequence of state building and nation building in different world regions?   

**Readings:**  

* Drogus, Carol Ann and Stephen Orvis. 2019.  “The State.” In Introducing Comparative Politics:  Concepts and Cases in Context. Los Angeles:  Sage. Read pages 40-48. https://drive.google.com/file/d/1J442vHPfFb3AWx7kat2aevSq3kCJvDib/view?usp=sharing

#### Friday, February 18

* Review the slide deck in the pdf of “Defining the State?” at https://drive.google.com/file/d/1H3i1tK9cL4hgdnAAje-SEUM_QYWUruYz/view?usp=sharing

* Power, Samantha. 2003. “How to Kill a Country. Turning a Breadbasket Into a Basket Case in Ten Easy Steps – The Robert Mugabe Way.” Atlantic Monthly. https://bit.ly/3CXsAKf  

**Video:**  

* 2006 Frontline Documentary: “Zimbabwe: Shadows and Lies.” https://www.youtube.com/watch?v=gltED2uOEek   
**Assignment:**   

Please watch the film and read the Samantha Power article while answering the following questions (these are directly from the reading guide: Be ready to share your answers to these questions in-class; the questions appear in Google Classroom).

This will be an excellent day to reflect on the crisis in Afghanistan, and we can determine the agenda as events unfold.

### Week 6

#### Monday, February 21

**Topics:**  

* What is nationalism?  

* How did the political identity of nationalism emerge?  

* What makes nationalism “successful” or not?   

**Readings:**  

* Anderson, Benedict. 1983. Introduction: Concepts and Definitions and Cultural Roots. In *Imagined Communities: Reflections on the Origins and Spread of Nationalism.* Read pages. 5-7. 
https://library.lcproxy.org/login?url=https://hdl.handle.net/2027/heb.01609

Midterm Exam Review

#### Wednesday, February 23

Midterm Exam

#### Friday, February 25

No class.  See you on February 28.

### Week 7

#### Monday, February 28 

What is nationalism?  What makes nationalism “successful” or not?

* Anderson, Benedict. 1983. Introduction: Concepts and Definitions and Cultural Roots. In *Imagined Communities: Reflections on the Origins and Spread of Nationalism.* Read pages. 5-7. (Reread from last week)
https://library.lcproxy.org/login?url=https://hdl.handle.net/2027/heb.01609

* King, Charles. 2010.  Extreme Politics: Nationalism, Violence, and the End of Eastern Europe.  Oxford:  Oxford University Press. Read “Theorizing Failure” pages 38-44
http://ebookcentral.proquest.com/lib/lewisclark/detail.action?docID=472310 

#### Wednesday, March 2

**Topic:**  

* What makes nationalism “successful” or not (redux)? The Case of Scotland 

**Readings:**  

* Robertson, Graeme. 2014. “Scotland Votes to Stay for Now.” The Washington Post: Monkey Cage. September 19, 2014.  
https://library.lcproxy.org/login?url=https://link.gale.com/apps/doc/A383094193/AONE?u=lacc_legal&sid=AONE&xid=81679d20

* The Economist. 2020. “How Coronavirus Strengthened Scottish Independence.”   https://library.lcproxy.org/login?url=https://link.gale.com/apps/doc/A631718787/AONE?u=lacc_legal&sid=AONE&xid=99d359c2  

* Recommended: Ross, Elliot. 2019.  Is Brexit Worth Scotland's Independence? *The Atlantic Monthly* July 31, 2019  https://bit.ly/3ssglAi

#### Friday, March 4

What is the distinction between a nation, ethnic group, or race?

Drogus, Carol Ann and Stephen Orvis. 2019.  “Ethnicity” and “Race.” In Introducing Comparative Politics:  Concepts and Cases in Context. Los Angeles:  Sage. Read pages 105-110. https://drive.google.com/file/d/1_R3IN7pBkYCqA086gPHA9S6rrIFvMJBG/view?usp=sharing

### Week 8

#### Monday, March 7

Why and when does nationalism result in political violence? The Case of Yugoslavia

We will the film *We Are All Neighbours* as a class:  https://primo.lclark.edu/permalink/f/1780deo/CP71325424690001451

Questions for reflection while watching the film:  Compare and contrast the relations amongst neighbors at the beginning and end of the film. What are some of the factors that you observed in the film that may help to explain why neighborly relations changed?
The main neighbors in the film: Nurija & Nusreta (Muslim), Ramsija (Muslim), Slavka (Catholic), Andja (Catholic)

Crepaz, Markus and Juerg Steiner. 2012.  “War in the Former Yugoslavia.” In European Democracies. Pearson. Read pages. 249-257. 
https://drive.google.com/file/d/1H4RJhCOPIXJXmbow9t-GMTav3NSrcC2x/view?usp=sharing

#### Wednesday, March 9

Why and when does nationalism result in political violence?  The Case of Yugoslavia

PLEASE NOTE: The reading guide contains a glossary of key names. Oberschall, Anthony. 2000. “The Manipulation of Ethnicity: From Ethnic Cooperation to Violence and War in Yugoslavia.” Ethnic and Racial Studies 23, no. 6: 982-987. 
http://library.lcproxy.org/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=sih&AN=3974511&site=ehost-live&scope=site 

Pass-Fail Assignent #2 Due  https://classroom.google.com/c/NDUwMzY0NzIwMzk5/a/NDUxNjY3NDE1MjM3/details

#### Friday, March 11

Why and when does nationalism result in political violence?  The Case of Yugoslavia

Oberschall, Anthony. 2000. “The Manipulation of Ethnicity: From Ethnic Cooperation to Violence and War in Yugoslavia.” Ethnic and Racial Studies 23, no. 6: 987-1001. 
http://library.lcproxy.org/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=sih&AN=3974511&site=ehost-live&scope=site 

PLEASE NOTE: The reading guide contains a glossary of key names. https://classroom.google.com/c/NDUwMzY0NzIwMzk5/m/NDUxMTIwMTY3NzAx/details

### Week 9

#### Monday, March 14

What impact do electoral systems have on the way political demands are processed and power is organized?  

How do the United Kingdom and the Netherlands illustrate the variety of electoral systems and their effects?

Taagepera, Rein and Matthew Shugart.  “Why Study Electoral Systems?” In Contending Perspectives in Comparative Politics. Washington D.C., CQ Press.  Read pages 165-168.
https://drive.google.com/file/d/10coHWxGLM0MBGs3y46nNTqZZHUsmZjrl/view?usp=sharing

Crepaz, Juerg and Markus Steiner. 2012. “The Netherlands.” In European Democracies Pearson.  Read pages 70-73. https://drive.google.com/file/d/1kI6sby5YLOCDQXkz6uZeIFdKcL3o9cSq/view?usp=sharing

#### Wednesday, March 16

Crepaz, Juerg and Markus Steiner. 2012. “The United Kingdom.” In European Democracies.  Pearson. Read pages 65-70. 
https://drive.google.com/file/d/1ucpl0SYC0LTZMXsGkPB8f7TtMRs1s21h/view?usp=sharing

Blumenau, Jack and Simon Hix. 2015. “What Would Britain Look Like Under Proportional Representation?” The Washington Post:  Monkey Cage. May 6, 2015. 
https://library.lcproxy.org/login?url=https://link.gale.com/apps/doc/A412534697/AONE?u=lacc_legal&sid=AONE&xid=197f6ed5

#### Friday, March 18

What are the strengths and weaknesses of different electoral systems?  
Norris, Pippa. 1997.  “Choosing Electoral Systems: Proportional, Majoritarian, and Mixed Systems.” International Political Science Review 18. No. 3.  Read only pages 306-311. http://journals.sagepub.com/doi/pdf/10.1177/019251297018003005 or here at: https://drive.google.com/file/d/1zusj7GJ6YPQOgfrEo5zQUVM1hNnWDCHr/view?usp=sharing  
Lijphart, Arend. 1998.  “Reforming the House: Three Moderately Radical Proposals.” P.S.: Political Science and Politics, 31, no.1: 10-13. 
https://library.lcproxy.org/login?url=https://www.jstor.org/stable/420424

Paper #1 Due
https://classroom.google.com/c/NDUwMzY0NzIwMzk5/a/NDUxNjcwMDg4MDI1/details

### Week 10 SPRING BREAK

#### Monday March 21 - Friday March 25

### Week 11

#### Monday, March 28

What are the strengths and weaknesses of different electoral systems?

Selway, Joel.  2020.  “Which kinds of democracies respond more effectively in a pandemic?” The Washington Post.  May 19    
https://www.washingtonpost.com/politics/2020/05/19/which-kinds-democracies-respond-more-effectively-pandemic/ or a PDF at https://drive.google.com/file/d/1SOGZlvPEoOcEYQUZcz9JqI8oXyGCxIf4/view?usp=sharing  

Lardeyret, Guy. 1991.  “The Problem with PR.”  Journal of Democracy, 2, no. 3:.30-35. 
https://library.lcproxy.org/login?url=https://muse.jhu.edu/article/225584
Gladdish, Ken. 1993.  “The Primacy of the Particular.” Journal of Democracy, 4, no.1: 53-65.
https://library.lcproxy.org/login?url=https://muse.jhu.edu/article/225487

#### Wednesday, March 30

Governing Institutions: What are the main differences between presidential and parliamentary systems?  What are the strengths and weaknesses of different constitutional forms?

Drogus, Carol Ann and Stephen Orvis. 2011.  “Parliamentary Rule in Britain and India” and  “Presidentialism in the United States and Brazil” In Introducing Comparative Politics:  Concepts and Cases in Context. Los Angeles: Sage. 

https://drive.google.com/file/d/1m-yDv8nUpJUvWNDaMFRAMe7wDi110owI/view?usp=sharing

Recommended: Recent Examples of No Confidence Votes

https://balkaninsight.com/2020/08/18/romanian-government-threatened-with-no-confidence-vote

https://www.bbc.com/news/uk-politics-48379730

https://www.nytimes.com/2018/12/22/world/americas/guyana-government-falls.html or a PDF at https://drive.google.com/file/d/1Yg48EXBFsapHM8u-Htc1f3vOs6uiUm9X/view?usp=sharing

#### Friday, April 1

What are the main differences between presidential and parliamentary systems?  What are the strengths and weaknesses of different constitutional forms?
Juan Linz. 1990. “The Perils of Presidentialism” Journal of Democracy 1, no. 1: 51-69. 
https://library.lcproxy.org/login?url=https://muse.jhu.edu/article/225694

Recommended application of Linz to the US:” Is US Presidentialist Democracy Failing?”
https://www.washingtonpost.com/opinions/is-the-us-presidentialist-democracy-failing/2016/02/10/37fa9ec8-d018-11e5-abc9-ea152f0b9561_story.html?utm_term=.a281aee08c11 or PDF at https://drive.google.com/file/d/1bCeioMlMvEieIt3XnMlmEmUxh-zltdyv/view?usp=sharing

### Week 12

#### Monday, April 4

What are the main differences between presidential and parliamentary systems?  What are the strengths and weaknesses of different constitutional forms?
READ 449-455; SKIM FOR MAIN POINTS 456-469. Scott Mainwaring and Matthew Shugart. 1997. “Juan Linz, Presidentialism and Democracy:  A Critical Appraisal” Comparative Politics. 29, no: 4: 449-469. 
https://library.lcproxy.org/login?url=https://www.jstor.org/stable/422014 

#### Wednesday, April 6

**Topics:**  

* What are the main differences between plurality vs. proportional represetation electoral systems?    
* How do the United Kingdom and the Netherlands illustrate the variety of electoral systems and their effects?  

**Readings:**  

* Review Crepaz, Juerg and Markus Steiner. 2012. “The United Kingdom.” In *European Democracies*. Pearson. Read pages 65-70. https://drive.google.com/file/d/1ucpl0SYC0LTZMXsGkPB8f7TtMRs1s21h/view?usp=sharing

* Blumenau, Jack and Simon Hix. 2015. “What Would Britain Look Like Under Proportional Representation?” The Washington Post:  Monkey Cage. May 6, 2015. https://bit.ly/3gutc0n  NOTE: Figures referenced in the article can be found at
https://bit.ly/3bYtbyT

* Selway, Joel.  2020.  “Which kinds of democracies respond more effectively in a pandemic?” The Washington Post.  May 19.  
https://www.washingtonpost.com/politics/2020/05/19/which-kinds-democracies-respond-more-effectively-pandemic/ or a PDF at https://drive.google.com/file/d/1SOGZlvPEoOcEYQUZcz9JqI8oXyGCxIf4/view?usp=sharing  
#### Friday April 8

Festival of Scholars:  No class today

### Week 13

#### Monday, April 11

What are the main differences between presidential and parliamentary systems?  What are the strengths and weaknesses of different constitutional forms?

Mainwaring, Scott and Matthew Shugart. 1997. “Juan Linz, Presidentialism and Democracy:  A Critical Appraisal” *Comparative Politics* 29, no: 4: 449-469. 
https://library.lcproxy.org/login?url=https://www.jstor.org/stable/422014  
Closely read 449-455; skim for main points in pp. 456-469. 

Democratic Institutions and Health Policy Case study: Ghana, Kenya, and Senegal

Grepin, Karen A. and Kim Yi Dionne. 2013. “Democratization and Universal Health Coverage: A Case Comparison of Ghana, Kenya, and Senegal.”  Global Health Governance. VI, no. 2: 1-23
http://blogs.shu.edu/ghg/files/2014/02/GHGJ_62_5-31_GREPIN_AND_DIONNE.pdf

#### Wednesday, April 13

How are non-democratic countries similar and different from one another?

Review Grepin & Dionne from April 11.  

Ezrow & Frantz, Read pages 1-5 (through mini section “Beyond Totalitarianism”); 19-23, 174-177 (Argentina); 208-2010 (Mexico); 225-227 (Central African Republic).

#### Friday, April 15

How do elections and parties work in non-democracies?
Ezrow & Frantz, Read pages 67-77
The Russian 2018 presidential election: https://edition.cnn.com/2018/03/19/europe/russia-election-reaction-intl/index.html


### Week 14
#### Monday, April 18

What causes non-democratic forms of rule?
Ezrow & Frantz, Read pages 33 (starting with Explaining the Type of Dictatorship)-50

Pass-Fail Assignent #3 Due https://classroom.google.com/c/NDUwMzY0NzIwMzk5/a/NDUxNjc1MzAzNTUw/details


#### Wednesday, April 20

Wednesday, April 14
What explains economic variations in non-democracies?
Review the group work question posted on our class notes.  At the start of class we’ll go into breakout rooms to discuss
Ezrow & Frantz, Ch. 7

#### Friday, April 22

What explains the dynamics and longevity of different types of authoritarian regimes?
Case study: military regimes

Ezrow & Frantz, pages 171-174, Read the cases of Argentina (review), Brazil, and Turkey

Fisher, Max. 2019. “A Very Dangerous Game: In Latin America Embattled Leaders Lean on Generals” New York Times October 31, 2019. 
https://www.nytimes.com/2019/10/31/world/americas/latin-america-protest-military.html or PDF at https://drive.google.com/file/d/1zmJG_kYMbda637R0omxoY15h4aXP3azm/view?usp=sharing

Recommended
Algeria:
https://www.washingtonpost.com/politics/2019/04/05/why-algerias-army-abandoned-bouteflika/?utm_term=.56be25cd5233&wpisrc=nl_cage&wpmm=1

Brazil:
https://www.reuters.com/article/us-brazil-politics/brazil-military-takes-up-coup-commemoration-at-bolsonaros-behest-idUSKCN1RC09J?utm_source=applenews

Sudan:
https://www.washingtonpost.com/politics/2019/04/15/four-things-know-about-sudans-coups/?noredirect=on&utm_term=.affcebfa0c1f


### Week 15
#### Monday, April 25

What explains the dynamics and longevity of different types of authoritarian regimes?
Case study: single party regimes
Ezrow & Frantz, 193-200, Read the cases of  Hungary, Malaysia and Mexico
Malaysia’s 2018 election that ended UMNO dominance: https://library.lcproxy.org/login?url=https://link.gale.com/apps/doc/A538839322/AONE?u=lacc_legal&sid=AONE&xid=e71736b3


#### Wednesday, April 27

What explains the dynamics and longevity of different types of authoritarian regimes?
Case study: personalist regimes
Ezrow & Frantz, 220-225, Read the cases of Central African Republic (review), Uganda, and Zaire.
Zimbabwe case study: “It’s been one year since Zimbabwe toppled Mugabe. Why isn’t it a democracy yet?”
https://www.washingtonpost.com/news/monkey-cage/wp/2018/11/17/its-been-one-year-since-zimbabwe-toppled-mugabe-why-isnt-it-a-democracy-yet/?utm_term=.f0ff16c31520&wpisrc=nl_cage&wpmm=1

#### Tuesday, May 4 1-4pm   
Final Exam


<!-- **Topic:** -->

<!-- What explains the dynamics and longevity of different types of authoritarian regimes? -->

<!-- **Readings:**   -->

<!-- *  Algeria: -->
<!-- https://www.washingtonpost.com/politics/2019/04/05/why-algerias-army-abandoned-bouteflika/?utm_term=.56be25cd5233&wpisrc=nl_cage&wpmm=1 -->

<!-- *  Brazil: -->
<!-- https://www.reuters.com/article/us-brazil-politics/brazil-military-takes-up-coup-commemoration-at-bolsonaros-behest-idUSKCN1RC09J?utm_source=applenews -->

<!-- *  Sudan: -->
<!-- https://www.washingtonpost.com/politics/2019/04/15/four-things-know-about-sudans-coups/?noredirect=on&utm_term=.affcebfa0c1f -->

<!-- *  Zimbabwe case study: “It’s been one year since Zimbabwe toppled Mugabe. Why isn’t it a democracy yet?” -->
<!-- https://www.washingtonpost.com/news/monkey-cage/wp/2018/11/17/its-been-one-year-since-zimbabwe-toppled-mugabe-why-isnt-it-a-democracy-yet/?utm_term=.f0ff16c31520&wpisrc=nl_cage&wpmm=1 -->

<!-- *  Follow up on Russia:  https://www.washingtonpost.com/politics/2021/08/25/russias-latest-crackdown-dissent-is-much-more-sweeping-than-ever-before/ -->

<!-- *  Brazil: https://www.washingtonpost.com/world/2021/07/23/brazil-bolsonaro/ -->

<!-- Future trajectories of non-democratic forms of rule -->
<!-- Case study: China -->
<!-- Ezrow & Frantz, 204-206 -->
<!-- Erica Frantz, Joseph Wright, and Barbara Geddes, “Did Xi Jinping just become China’s Strongman?”  -->
<!-- https://library.lcproxy.org/login?url=https://link.gale.com/apps/doc/A530900222/AONE?u=lacc_legal&sid=AONE&xid=ad630011 -->

<!-- Recommended: -->
<!-- https://foreignpolicy.com/2018/10/15/chinas-great-leap-backward-xi-jinping/ -->


<!-- **Assignment:** -->
<!-- Paper #2 Due  -->

<!-- ### Week 16 -->
<!-- #### Tuesday, May 4 1-4pm -->
<!-- Final Exam -->


<!-- * Presidential vs. Parliamentary democracies: the example of Canada. -->

<!-- **Readings:**   -->

<!-- Malloy, Jonathan and Paul J. Quirk. 2019. Executive Leadership and the Legislative Process.  in *The United States and Canada: How Two Democracies Differ and Why it Matters* ed. Paul J. Quirk. Read pp. 79-87. (i.e., pages 1-9 of the pdf). https://bit.ly/3sHfEU5 -->

<!-- Way, Lucan Ahmad and Steven Levitsky. 2019. "How autocrats can rig the game and damage democracy." The Washington Post. January 4.  -->
<!-- https://library.lcproxy.org/login?url=https://link.gale.com/apps/doc/A568353459/AONE?u=lacc_legal&sid=AONE&xid=aa06d8b0 -->
<!-- Amanda Taub. 2016.  “How Stable Are Democracies? ‘Warning Signs are Flashing Red’ The New York Times. November 29. https://www.nytimes.com/2016/11/29/world/americas/western-liberal-democracy.html -->
<!-- Yascha Mounk and Roberto Stefan. 2016. “Yes People Are Really Turning Away from Democracy” The Washington Post. December 8.  -->
<!-- https://library.lcproxy.org/login?url=https://link.gale.com/apps/doc/A473340695/AONE?u=lacc_legal&sid=AONE&xid=257926df -->

<!-- Cristina Bodea and Christian House. 2020. “The longer-term coronavirus fallout could erode democracy.  Here’s how that could play out.” The Washington Post. August 4. https://www.washingtonpost.com/politics/2020/08/04/longer-term-coronavirus-fallout-could-erode-democracy-heres-how-that-could-play-out/ -->
<!-- Roberto Stefan Foa and Andrew James Klassen. 2020. “How democracies can survive dilemmas like the coronavirus.” The Washington Post. May 13.  https://www.washingtonpost.com/politics/2020/05/13/how-democracies-can-survive-crises-like-coronavirus/ -->

<!-- * Bruce, Daryl.  2021.  Canadian Civics 101: Why Justin Trudeau Can Call an Election. Medium Aug 5, 2021 -->
<!-- https://medium.com/the-partnered-pen/canadian-civics-101-why-justin-trudeau-can-call-an-election-969ea9db8297 -->

